In [1]:
import numpy as np
import pandas as pd

# Problem 1
B stands for Birds, and P stands for People, 2 letters like BP stands for Birds identified as People

In [2]:
#inside the array, each elements are ([BB,PB],[BP,PP])
NN=np.array([[45,3],[5,47]]) # ([Col1],[Col2])
NA=np.array([[47,1],[11,42]]) #Shouldn't this one sums up to 101?

In [3]:
NN[:,0]

array([45,  5])

### 1A
The mistakes are counted from non-diagonal term, which NN has 3+5 = 8 out of 100, and NA has 1+11 = 12 out of 101. So, NN makes fewer mistakes.
### 1B
For the zoo, we want to minimize birds identify as people, so the lower BP the better. NN has 3/100 while NA has 1/101, so NA is better.
### 1C
The sum of [BB,BP] is now 99 and [PB,PP] is 1.

In [4]:
prow=[99,1]
namecol=["True B%","True P%"]
namerow=["As B%","As P%"]
def newarr(arr,prow=prow):
    new=np.array([row/np.sum(row)*pr for row,pr in zip(arr,prow)])
    return pd.DataFrame(new.T.round(3),columns=namecol,index=namerow) #Transpose the "new" array so that it is [[Row1],[Row2]] and round it to 3 decimals

In [5]:
newarr(NN)

       True B%  True P%
As B%   92.812    0.096
As P%    6.188    0.904

In [6]:
newarr(NA)

       True B%  True P%
As B%   96.938    0.208
As P%    2.062    0.792

# Problem 2
### 2A
The exponential distribution is a special case of gamma distribution where $\alpha = 1$.
$$f(x;\alpha,\lambda) = \frac{\lambda^{\alpha}}{\Gamma(\alpha)} x^{\alpha-1} e^{-\lambda x}$$
$$f(x;1,\lambda) = \frac{\lambda^{1}}{\Gamma(1)} x^{1-1} e^{-\lambda x} = \lambda e^{-\lambda x}$$
So, sum of 2 identical exponential distribution is gamma distribution with $\alpha = 2$.
$$f(x;2,\lambda) = \frac{\lambda^{2}}{\Gamma(2)} x^{2-1} e^{-\lambda x} = \lambda^2 x e^{-\lambda x}$$
### 2B
The normal distribution has PDF that looks like this: $P(x) = \frac{1}{\sqrt{2\pi}\sigma} e^{-\frac{x^2}{2\sigma^2}}$ \
So, PDF of 2 normal distributions would be: $P(x_1,x_2) = P(x_1) P(x_2) = \frac{1}{2\pi \sigma^2} e^{-\frac{x_1^2+x_2^2}{2\sigma^2}}$ \
Then, the PDF of the ratio of the 2, which is defined as $z = \frac{x_1}{x_2}$, is:
$$P(z) = \int_{-\infty}^{\infty} |x_2| P(x_1,x_2) dx_2 = \frac{1}{2\pi \sigma^2} 2\int_{0}^{\infty} e^{-\frac{z^2+1}{2\sigma^2}x_2^2} \frac{dx_2^2}{2} 
= -\frac{2\sigma^2}{2\pi \sigma^2 (z^2+1)} e^{-\frac{z^2+1}{2\sigma^2}x_2^2} \bigg|_{x_2=0}^{\infty} = \frac{1}{\pi (z^2+1)}$$
### 2C
The amplitude of $x+iy$ could be written as radius $r=\sqrt{x^2+y^2}\geq 0$. We can reuse to PDF of 2 normal distributions from 2B but with $(x_1,x_2) \rightarrow (x,y)$.
$$P(x,y) = \frac{1}{2\pi \sigma^2} e^{-\frac{x^2+y^2}{2\sigma^2}} = \frac{1}{2\pi \sigma^2} e^{-\frac{r^2}{2\sigma^2}}$$
$$P(r) = \int_0^{2\pi} P(r,\theta) d\theta = \int_0^{2\pi} |r| P(x,y) d\theta = \int_0^{2\pi} \frac{|r|}{2\pi \sigma^2} e^{-\frac{r^2}{2\sigma^2}} d\theta 
= \frac{2\pi|r|}{2\pi \sigma^2} e^{-\frac{r^2}{2\sigma^2}}$$
Since $r\geq 0$,
$$P(r) = \frac{r}{\sigma^2} e^{-\frac{r^2}{2\sigma^2}}$$
This looks exactly like Rayleigh distribution.